import fs from "node:fs";
import { afterAll, beforeAll, describe, it } from "vitest";
import { assertFails, assertSucceeds, initializeTestEnvironment } from "@firebase/rules-unit-testing";
import { get, ref, set, update } from "firebase/database";

let env;const projectId="classpad-rules-test",classId="class123",studentId="student123",token="abcdefghijklmnopqrstuvwx";
beforeAll(async()=>{env=await initializeTestEnvironment({projectId,database:{rules:fs.readFileSync("database.rules.json","utf8"),host:"127.0.0.1",port:9000}});await env.withSecurityRulesDisabled(async context=>set(ref(context.database()),{classes:{[classId]:{title:"測試",className:"",activityName:"",createdAt:1,updatedAt:1,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:1,admins:{teacher:true},studentOrder:{[studentId]:0}}},students:{[studentId]:{classId,boardToken:token,seatNumber:"01",displayName:"小明",studentUid:"student",enabled:true,locked:false,createdAt:1,updatedAt:1}},boardLookup:{[token]:{classId,studentId}},boards:{[token]:{meta:{classId,studentId,revision:0,updatedAt:1}}},userClasses:{teacher:{[classId]:true}},teacherSlots:{[classId]:{1:"teacher"}}}));});
afterAll(()=>env?.cleanup());
const stroke=(uid,color="#112233")=>({id:"stroke_1",tool:"pen",color,width:4,opacity:1,points:[[.1,.1,.5,0],[.2,.2,.5,10]],createdAt:2,authorUid:uid});
describe("Realtime Database 權限",()=>{
  it("老師可讀課堂與寫批注",async()=>{const db=env.authenticatedContext("teacher").database();await assertSucceeds(get(ref(db,`classes/${classId}`)));await assertSucceeds(set(ref(db,`boards/${token}/teacherStrokes/stroke_1`),stroke("teacher")));});
  it("學生可寫自己的筆跡且不能寫老師圖層",async()=>{const db=env.authenticatedContext("student").database();await assertSucceeds(set(ref(db,`boards/${token}/studentStrokes/stroke_1`),stroke("student")));await assertFails(set(ref(db,`boards/${token}/teacherStrokes/stroke_2`),{...stroke("student"),id:"stroke_2"}));});
  it("學生不能修改姓名或把自己加入管理員",async()=>{const db=env.authenticatedContext("student").database();await assertFails(update(ref(db,`students/${studentId}`),{displayName:"惡意修改"}));await assertFails(set(ref(db,`classes/${classId}/admins/student`),true));});
  it("其他人不能讀學生資料或筆跡",async()=>{const db=env.authenticatedContext("other").database();await assertFails(get(ref(db,`students/${studentId}`)));await assertFails(get(ref(db,`boards/${token}/studentStrokes`)));});
  it("拒絕非法顏色與未登入存取",async()=>{const db=env.authenticatedContext("student").database();await assertFails(set(ref(db,`boards/${token}/studentStrokes/stroke_1`),stroke("student","red")));await assertFails(get(ref(env.unauthenticatedContext().database(),`boardLookup/${token}`)));});
  it("新裝置可用短效單次連結取得老師權限",async()=>{const inviteToken="ABCDEFGHJKLMNPQRSTUVWX23",now=Date.now(),teacherDb=env.authenticatedContext("teacher").database(),monitorDb=env.authenticatedContext("monitor").database();await assertSucceeds(set(ref(teacherDb,`teacherInvites/${inviteToken}`),{classId,createdBy:"teacher",createdAt:now,expiresAt:now+600000}));await assertSucceeds(set(ref(monitorDb,`teacherInvites/${inviteToken}/claimedBy`),"monitor"));await assertSucceeds(set(ref(monitorDb,`teacherClaims/${classId}/monitor`),inviteToken));await assertSucceeds(set(ref(monitorDb,`teacherSlots/${classId}/2`),"monitor"));await assertSucceeds(set(ref(monitorDb,`classes/${classId}/admins/monitor`),true));await assertSucceeds(set(ref(monitorDb,`userClasses/monitor/${classId}`),true));await assertSucceeds(get(ref(monitorDb,`classes/${classId}`)));await assertSucceeds(update(ref(monitorDb),{[`teacherClaims/${classId}/monitor`]:null,[`teacherInvites/${inviteToken}`]:null}));});
  it("老師授權連結不能被第二個裝置重複使用",async()=>{const inviteToken="abcdefghjkmnpqrstuvwx234",now=Date.now(),teacherDb=env.authenticatedContext("teacher").database(),firstDb=env.authenticatedContext("first-monitor").database(),otherDb=env.authenticatedContext("other-monitor").database();await assertSucceeds(set(ref(teacherDb,`teacherInvites/${inviteToken}`),{classId,createdBy:"teacher",createdAt:now,expiresAt:now+600000}));await assertSucceeds(set(ref(firstDb,`teacherInvites/${inviteToken}/claimedBy`),"first-monitor"));await assertFails(set(ref(otherDb,`teacherInvites/${inviteToken}/claimedBy`),"other-monitor"));await assertFails(set(ref(otherDb,`teacherClaims/${classId}/other-monitor`),inviteToken));await assertFails(set(ref(otherDb,`classes/${classId}/admins/other-monitor`),true));});
  it("過期的老師授權連結不能被使用",async()=>{const inviteToken="23456789ABCDEFGHJKLMNPQR",otherDb=env.authenticatedContext("expired-monitor").database();await env.withSecurityRulesDisabled(async context=>set(ref(context.database(),`teacherInvites/${inviteToken}`),{classId,createdBy:"teacher",createdAt:1,expiresAt:2}));await assertFails(set(ref(otherDb,`teacherInvites/${inviteToken}/claimedBy`),"expired-monitor"));});
  it("每個課堂最多五台老師裝置",async()=>{const limitClass="class-limit",now=Date.now(),teacherDb=env.authenticatedContext("limit-teacher").database(),tokens=[3,4,5,6,7].map(n=>`ABCDEFGHJKLMNPQRSTUVWX2${n}`);await env.withSecurityRulesDisabled(async context=>{await set(ref(context.database(),`classes/${limitClass}`),{title:"五台裝置測試",className:"",activityName:"",createdAt:1,updatedAt:1,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:0,admins:{"limit-teacher":true},studentOrder:{}});await set(ref(context.database(),`teacherSlots/${limitClass}/1`),"limit-teacher");});for(const inviteToken of tokens)await assertSucceeds(set(ref(teacherDb,`teacherInvites/${inviteToken}`),{classId:limitClass,createdBy:"limit-teacher",createdAt:now,expiresAt:now+600000}));for(let i=0;i<4;i++){const uid=`limit-monitor-${i+1}`,db=env.authenticatedContext(uid).database();await assertSucceeds(set(ref(db,`teacherInvites/${tokens[i]}/claimedBy`),uid));await assertSucceeds(set(ref(db,`teacherClaims/${limitClass}/${uid}`),tokens[i]));await assertSucceeds(set(ref(db,`teacherSlots/${limitClass}/${i+2}`),uid));await assertSucceeds(set(ref(db,`classes/${limitClass}/admins/${uid}`),true));}const sixthUid="limit-monitor-5",sixthDb=env.authenticatedContext(sixthUid).database();await assertSucceeds(set(ref(sixthDb,`teacherInvites/${tokens[4]}/claimedBy`),sixthUid));await assertSucceeds(set(ref(sixthDb,`teacherClaims/${limitClass}/${sixthUid}`),tokens[4]));await assertFails(set(ref(sixthDb,`teacherSlots/${limitClass}/5`),sixthUid));await assertFails(set(ref(sixthDb,`classes/${limitClass}/admins/${sixthUid}`),true));await assertFails(set(ref(teacherDb,"teacherInvites/JKLMNPQRSTUVWX23456789AB"),{classId:limitClass,createdBy:"limit-teacher",createdAt:now,expiresAt:now+600000}));});
});
