import fs from "node:fs";
import { afterAll, beforeAll, describe, it } from "vitest";
import { assertFails, assertSucceeds, initializeTestEnvironment } from "@firebase/rules-unit-testing";
import { get, ref, set, update } from "firebase/database";

let env;const projectId="classpad-rules-test",classId="class123",studentId="student123",token="abcdefghijklmnopqrstuvwx";
beforeAll(async()=>{env=await initializeTestEnvironment({projectId,database:{rules:fs.readFileSync("database.rules.json","utf8"),host:"127.0.0.1",port:9000}});const now=Date.now(),pages={main:{id:"main",order:0,createdAt:1,createdBy:"teacher"},page_ABCDEF:{id:"page_ABCDEF",order:1,createdAt:2,createdBy:"teacher"}};await env.withSecurityRulesDisabled(async context=>set(ref(context.database()),{classes:{[classId]:{title:"測試",className:"",activityName:"",createdAt:now,expiresAt:now+10800000,updatedAt:now,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:1,admins:{teacher:true},studentOrder:{[studentId]:0},boardPages:pages}},students:{[studentId]:{classId,boardToken:token,seatNumber:"01",displayName:"小明",studentUid:"student",enabled:true,locked:false,createdAt:1,updatedAt:1}},boardLookup:{[token]:{classId,studentId}},boardPages:{[token]:pages},boards:{[token]:{meta:{classId,studentId,revision:0,updatedAt:1}}},userClasses:{teacher:{[classId]:true}},teacherKeys:{[classId]:"123456"}}));});
afterAll(()=>env?.cleanup());
const stroke=(uid,color="#112233")=>({id:"stroke_1",tool:"pen",color,width:4,opacity:1,points:[[.1,.1,.5,0],[.2,.2,.5,10]],createdAt:2,authorUid:uid});
const stickyNote=(uid,overrides={})=>({id:"note_1",text:"請看這裡",color:"yellow",x:.1,y:.1,width:.3,height:.2,createdAt:2,updatedAt:2,authorUid:uid,...overrides});
describe("Realtime Database 權限",()=>{
  it("新課程只能設定為建立後 3 小時到期",async()=>{const db=env.authenticatedContext("new-class-teacher").database(),now=Date.now(),base={title:"三小時課堂",className:"",activityName:"",createdAt:now,updatedAt:now,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:0,admins:{"new-class-teacher":true}};await assertSucceeds(set(ref(db,"classes/three-hour-class"),{...base,expiresAt:now+10_800_000}));await assertFails(set(ref(db,"classes/twelve-hour-class"),{...base,expiresAt:now+43_200_000}));});
  it("老師可讀課堂與寫批注",async()=>{const db=env.authenticatedContext("teacher").database();await assertSucceeds(get(ref(db,`classes/${classId}`)));await assertSucceeds(set(ref(db,`boards/${token}/teacherStrokes/stroke_1`),stroke("teacher")));});
  it("老師批注只接受布林值的平滑設定",async()=>{const db=env.authenticatedContext("teacher").database();await assertSucceeds(set(ref(db,`boards/${token}/teacherStrokes/stroke_1`),{...stroke("teacher"),smooth:true}));await assertFails(set(ref(db,`boards/${token}/teacherStrokes/stroke_1`),{...stroke("teacher"),smooth:"true"}));});
  it("老師可管理便條貼，學生只能讀取",async()=>{const teacherDb=env.authenticatedContext("teacher").database(),studentDb=env.authenticatedContext("student").database();await assertSucceeds(set(ref(teacherDb,`boards/${token}/stickyNotes/note_1`),stickyNote("teacher")));await assertSucceeds(get(ref(studentDb,`boards/${token}/stickyNotes/note_1`)));await assertFails(update(ref(studentDb,`boards/${token}/stickyNotes/note_1`),{x:.2}));await assertSucceeds(update(ref(teacherDb,`boards/${token}/stickyNotes/note_1`),{x:.2,updatedAt:3}));await assertSucceeds(set(ref(teacherDb,`boards/${token}/stickyNotes/note_1`),null));});
  it("拒絕超出白板或使用未知顏色的便條貼",async()=>{const db=env.authenticatedContext("teacher").database();await assertFails(set(ref(db,`boards/${token}/stickyNotes/note_1`),stickyNote("teacher",{x:.9,width:.3})));await assertFails(set(ref(db,`boards/${token}/stickyNotes/note_1`),stickyNote("teacher",{color:"purple"})));});
  it("學生可寫自己的筆跡且不能寫老師圖層",async()=>{const db=env.authenticatedContext("student").database();await assertSucceeds(set(ref(db,`boards/${token}/studentStrokes/stroke_1`),stroke("student")));await assertFails(set(ref(db,`boards/${token}/teacherStrokes/stroke_2`),{...stroke("student"),id:"stroke_2"}));});
  it("老師與學生可更新最後書寫頁，並拒絕不存在的頁面",async()=>{const teacherDb=env.authenticatedContext("teacher").database(),studentDb=env.authenticatedContext("student").database();await assertSucceeds(update(ref(studentDb,`boards/${token}/meta`),{lastWrittenPageId:"main",lastWrittenAt:10,lastWrittenLayer:"studentStrokes",updatedAt:10,revision:10}));await assertSucceeds(update(ref(teacherDb,`boards/${token}/meta`),{lastWrittenPageId:"page_ABCDEF",lastWrittenAt:20,lastWrittenLayer:"teacherStrokes",updatedAt:20,revision:20}));await assertFails(update(ref(teacherDb,`boards/${token}/meta`),{lastWrittenPageId:"page_NOTFOUND",lastWrittenAt:30,lastWrittenLayer:"teacherStrokes",updatedAt:30,revision:30}));});
  it("新學生只用專屬網址即可完成首次綁定並開啟白板",async()=>{const freshStudent="fresh-student",freshToken="ZYXWVUTSzyxwvuts87654321",uid="fresh-device",db=env.authenticatedContext(uid).database(),pages={main:{id:"main",order:0,createdAt:1,createdBy:"teacher"}},student={classId,boardToken:freshToken,seatNumber:"02",displayName:"新學生",enabled:true,locked:false,createdAt:1,updatedAt:1};await env.withSecurityRulesDisabled(async context=>update(ref(context.database()),{[`students/${freshStudent}`]:student,[`boardLookup/${freshToken}`]:{classId,studentId:freshStudent},[`boardPages/${freshToken}`]:pages,[`boards/${freshToken}/meta`]:{classId,studentId:freshStudent,revision:0,updatedAt:1}}));await assertSucceeds(get(ref(db,`boardLookup/${freshToken}`)));await assertSucceeds(get(ref(db,`students/${freshStudent}`)));await assertSucceeds(set(ref(db,`students/${freshStudent}`),{...student,studentUid:uid,updatedAt:2}));await assertSucceeds(get(ref(db,`boardPages/${freshToken}`)));await assertSucceeds(get(ref(db,`boards/${freshToken}/studentStrokes`)));await assertSucceeds(set(ref(db,`presence/${classId}/${freshStudent}`),{uid,online:true,drawing:false,currentPageId:"main",lastSeen:2}));});
  it("老師可建立共用頁序，學生只能讀取",async()=>{const teacherDb=env.authenticatedContext("teacher").database(),studentDb=env.authenticatedContext("student").database(),pages={main:{id:"main",order:0,createdAt:1,createdBy:"teacher"},page_ABCDEF:{id:"page_ABCDEF",order:1,createdAt:2,createdBy:"teacher"}};await assertSucceeds(update(ref(teacherDb),{[`classes/${classId}/boardPages`]:pages,[`boardPages/${token}`]:pages}));await assertSucceeds(get(ref(studentDb,`boardPages/${token}`)));await assertFails(set(ref(studentDb,`boardPages/${token}/page_GHIJKL`),{id:"page_GHIJKL",order:2,createdAt:3,createdBy:"student"}));});
  it("老師可設定、移動與替換每頁底圖，學生只能讀取",async()=>{const teacherDb=env.authenticatedContext("teacher").database(),studentDb=env.authenticatedContext("student").database(),fileId="1AbCdEfGhIjKlMnOpQrStUvWxYz234567",backgroundImage={sourceUrl:`https://drive.google.com/file/d/${fileId}/view?usp=sharing`,imageUrl:`https://drive.google.com/thumbnail?id=${fileId}&sz=w2000`,scale:.8,x:.5,y:.5,updatedAt:3,updatedBy:"teacher"};await assertSucceeds(update(ref(teacherDb),{[`classes/${classId}/boardPages/main/backgroundImage`]:backgroundImage,[`boardPages/${token}/main/backgroundImage`]:backgroundImage}));await assertSucceeds(get(ref(studentDb,`boardPages/${token}/main/backgroundImage`)));await assertFails(update(ref(studentDb,`boardPages/${token}/main/backgroundImage`),{scale:1.2}));await assertSucceeds(update(ref(teacherDb),{[`classes/${classId}/boardPages/main/backgroundImage/scale`]:1.2,[`classes/${classId}/boardPages/main/backgroundImage/x`]:.25,[`classes/${classId}/boardPages/main/backgroundImage/y`]:.75,[`classes/${classId}/boardPages/main/backgroundImage/updatedAt`]:4,[`boardPages/${token}/main/backgroundImage/scale`]:1.2,[`boardPages/${token}/main/backgroundImage/x`]:.25,[`boardPages/${token}/main/backgroundImage/y`]:.75,[`boardPages/${token}/main/backgroundImage/updatedAt`]:4}));await assertFails(update(ref(teacherDb),{[`classes/${classId}/boardPages/main/backgroundImage/x`]:1.1,[`boardPages/${token}/main/backgroundImage/x`]:1.1}));await assertFails(update(ref(teacherDb),{[`classes/${classId}/boardPages/main/backgroundImage/imageUrl`]:"https://example.com/image.png",[`boardPages/${token}/main/backgroundImage/imageUrl`]:"https://example.com/image.png"}));});
  it("學生可寫自己的新增頁，但不能寫老師圖層",async()=>{const db=env.authenticatedContext("student").database();await assertSucceeds(set(ref(db,`boards/${token}/pages/page_ABCDEF/studentStrokes/stroke_1`),stroke("student")));await assertFails(set(ref(db,`boards/${token}/pages/page_ABCDEF/teacherStrokes/stroke_2`),{...stroke("student"),id:"stroke_2"}));});
  it("學生 presence 只能使用存在的頁碼",async()=>{const db=env.authenticatedContext("student").database(),base={uid:"student",online:true,drawing:false,lastSeen:3};await assertSucceeds(set(ref(db,`presence/${classId}/${studentId}`),{...base,currentPageId:"page_ABCDEF",lastWrittenPageId:"main"}));await assertFails(set(ref(db,`presence/${classId}/${studentId}`),{...base,currentPageId:"page_NOTFOUND"}));});
  it("展示裝置不限數量，且只能被動讀取老師目前投影的學生與頁面",async()=>{const displayToken="RSTUVWXYZabcdefghjkmnpqr",teacherDb=env.authenticatedContext("teacher").database(),displayDb=env.authenticatedContext("display-screen").database(),secondDisplayDb=env.authenticatedContext("display-screen-2").database();await assertSucceeds(set(ref(teacherDb,`classes/${classId}/displayToken`),displayToken));await assertSucceeds(set(ref(teacherDb,`displays/${displayToken}`),{classId,active:false,updatedAt:4,updatedBy:"teacher"}));await assertFails(set(ref(displayDb,"displaySessions/display-screen"),{displayToken,boardToken:token,updatedAt:4}));await assertSucceeds(set(ref(teacherDb,`displays/${displayToken}`),{classId,active:true,studentId,boardToken:token,pageId:"main",label:"01 小明",followStudent:true,updatedAt:5,updatedBy:"teacher"}));await assertSucceeds(set(ref(displayDb,"displaySessions/display-screen"),{displayToken,boardToken:token,updatedAt:5}));await assertSucceeds(set(ref(secondDisplayDb,"displaySessions/display-screen-2"),{displayToken,boardToken:token,updatedAt:5}));await assertSucceeds(get(ref(displayDb,`boards/${token}/studentStrokes`)));await assertSucceeds(get(ref(secondDisplayDb,`boards/${token}/studentStrokes`)));await assertFails(get(ref(displayDb,`boards/${token}/pages/page_ABCDEF/studentStrokes`)));await assertSucceeds(get(ref(displayDb,`boardPages/${token}`)));await assertFails(set(ref(displayDb,`boards/${token}/studentStrokes/display_stroke`),{...stroke("display-screen"),id:"display_stroke"}));await assertFails(get(ref(displayDb,"boards/not-the-selected-board/studentStrokes")));await assertSucceeds(update(ref(teacherDb,`displays/${displayToken}`),{pageId:"page_ABCDEF",updatedAt:6}));await assertSucceeds(get(ref(displayDb,`boards/${token}/pages/page_ABCDEF/studentStrokes`)));await assertSucceeds(get(ref(secondDisplayDb,`boards/${token}/pages/page_ABCDEF/studentStrokes`)));await assertFails(get(ref(displayDb,`boards/${token}/studentStrokes`)));await assertSucceeds(set(ref(teacherDb,`displays/${displayToken}`),{classId,active:false,updatedAt:7,updatedBy:"teacher"}));await assertFails(get(ref(displayDb,`boards/${token}/pages/page_ABCDEF/studentStrokes`)));await assertFails(get(ref(secondDisplayDb,`boards/${token}/pages/page_ABCDEF/studentStrokes`)));await assertSucceeds(set(ref(displayDb,"displaySessions/display-screen"),null));await assertSucceeds(set(ref(secondDisplayDb,"displaySessions/display-screen-2"),null));});
  it("學生不能修改姓名或把自己加入管理員",async()=>{const db=env.authenticatedContext("student").database();await assertFails(update(ref(db,`students/${studentId}`),{displayName:"惡意修改"}));await assertFails(set(ref(db,`classes/${classId}/admins/student`),true));});
  it("其他人不能讀學生資料或筆跡",async()=>{const db=env.authenticatedContext("other").database();await assertFails(get(ref(db,`students/${studentId}`)));await assertFails(get(ref(db,`boards/${token}/studentStrokes`)));});
  it("拒絕非法顏色與未登入存取",async()=>{const db=env.authenticatedContext("student").database();await assertFails(set(ref(db,`boards/${token}/studentStrokes/stroke_1`),stroke("student","red")));await assertFails(get(ref(env.unauthenticatedContext().database(),`boardLookup/${token}`)));});
  it("學生人數與順序上限為 80",async()=>{const db=env.authenticatedContext("teacher").database();await assertSucceeds(set(ref(db,`classes/${classId}/studentCount`),80));await assertFails(set(ref(db,`classes/${classId}/studentCount`),81));await assertSucceeds(set(ref(db,`classes/${classId}/studentOrder/student080`),79));await assertFails(set(ref(db,`classes/${classId}/studentOrder/student081`),80));});
  it("只有老師可釘選本課堂學生",async()=>{const teacherDb=env.authenticatedContext("teacher").database(),studentDb=env.authenticatedContext("student").database();await assertSucceeds(set(ref(teacherDb,`classes/${classId}/pinnedStudents/${studentId}`),true));await assertFails(set(ref(studentDb,`classes/${classId}/pinnedStudents/${studentId}`),true));await assertFails(set(ref(teacherDb,`classes/${classId}/pinnedStudents/not-in-class`),true));await assertSucceeds(set(ref(teacherDb,`classes/${classId}/pinnedStudents/${studentId}`),null));});
  it("新裝置可用短效單次連結取得老師權限",async()=>{const inviteToken="ABCDEFGHJKLMNPQRSTUVWX23",now=Date.now(),teacherDb=env.authenticatedContext("teacher").database(),monitorDb=env.authenticatedContext("monitor").database();await assertSucceeds(update(ref(teacherDb),{[`teacherInvites/${inviteToken}`]:{classId,createdBy:"teacher",createdAt:now,expiresAt:now+600000},[`classes/${classId}/teacherInviteTokens/${inviteToken}`]:true}));await assertSucceeds(set(ref(monitorDb,`teacherInvites/${inviteToken}/claimedBy`),"monitor"));await assertSucceeds(set(ref(monitorDb,`teacherClaims/${classId}/monitor`),inviteToken));await assertSucceeds(set(ref(monitorDb,`classes/${classId}/admins/monitor`),true));await assertSucceeds(set(ref(monitorDb,`userClasses/monitor/${classId}`),true));await assertSucceeds(get(ref(monitorDb,`classes/${classId}`)));await assertSucceeds(update(ref(monitorDb),{[`teacherClaims/${classId}/monitor`]:null,[`teacherInvites/${inviteToken}`]:null,[`classes/${classId}/teacherInviteTokens/${inviteToken}`]:null}));});
  it("永久老師連結可用六位數密鑰授權多台相同權限裝置",async()=>{
    const keyClass="class-key-access",key="012345",now=Date.now(),teacherDb=env.authenticatedContext("key-teacher").database(),firstDb=env.authenticatedContext("key-monitor-1").database(),secondDb=env.authenticatedContext("key-monitor-2").database();
    await env.withSecurityRulesDisabled(async context=>update(ref(context.database()),{
      [`classes/${keyClass}`]:{title:"密鑰課堂",className:"",activityName:"",createdAt:now,expiresAt:now+10800000,updatedAt:now,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:0,admins:{"key-teacher":true}},
      [`userClasses/key-teacher/${keyClass}`]:true,
      [`teacherKeys/${keyClass}`]:key
    }));
    await assertSucceeds(get(ref(teacherDb,`teacherKeys/${keyClass}`)));
    await assertFails(get(ref(firstDb,`teacherKeys/${keyClass}`)));
    await assertFails(set(ref(firstDb,`teacherKeyClaims/${keyClass}/key-monitor-1`),"999999"));
    await assertSucceeds(set(ref(firstDb,`teacherKeyClaims/${keyClass}/key-monitor-1`),key));
    await assertSucceeds(set(ref(firstDb,`classes/${keyClass}/admins/key-monitor-1`),true));
    await assertSucceeds(set(ref(firstDb,`userClasses/key-monitor-1/${keyClass}`),true));
    await assertSucceeds(set(ref(firstDb,`teacherKeyClaims/${keyClass}/key-monitor-1`),null));
    await assertSucceeds(set(ref(secondDb,`teacherKeyClaims/${keyClass}/key-monitor-2`),key));
    await assertSucceeds(set(ref(secondDb,`classes/${keyClass}/admins/key-monitor-2`),true));
    await assertSucceeds(set(ref(secondDb,`userClasses/key-monitor-2/${keyClass}`),true));
    await assertSucceeds(update(ref(firstDb,`classes/${keyClass}`),{activityName:"第一台管理",updatedAt:2}));
    await assertSucceeds(update(ref(secondDb,`classes/${keyClass}`),{activityName:"第二台管理",updatedAt:3}));
    const addedStudent="key-added-student",addedBoard="ABCDEFGHabcdefgh23456789",pages={main:{id:"main",order:0,createdAt:1,createdBy:"key-teacher"}};
    await assertSucceeds(set(ref(secondDb,`boardLookup/${addedBoard}`),{studentId:addedStudent,classId:keyClass}));
    await assertSucceeds(update(ref(secondDb),{
      [`students/${addedStudent}`]:{classId:keyClass,boardToken:addedBoard,seatNumber:"01",displayName:"密鑰新增學生",studentUid:null,enabled:true,locked:false,createdAt:4,updatedAt:4},
      [`classes/${keyClass}/studentOrder/${addedStudent}`]:0,
      [`classes/${keyClass}/studentCount`]:1,
      [`classes/${keyClass}/updatedAt`]:4,
      [`boards/${addedBoard}/meta`]:{classId:keyClass,studentId:addedStudent,revision:0,updatedAt:4},
      [`boardPages/${addedBoard}`]:pages
    }));
    await assertSucceeds(update(ref(secondDb),{
      [`classes/${keyClass}`]:null,
      [`userClasses/key-teacher/${keyClass}`]:null,
      [`userClasses/key-monitor-1/${keyClass}`]:null,
      [`userClasses/key-monitor-2/${keyClass}`]:null,
      [`teacherSlots/${keyClass}`]:null,
      [`teacherKeys/${keyClass}`]:null,
      [`teacherKeyClaims/${keyClass}`]:null,
      [`students/${addedStudent}`]:null,
      [`boardLookup/${addedBoard}`]:null,
      [`boards/${addedBoard}`]:null,
      [`boardPages/${addedBoard}`]:null
    }));
  });
  it("同一課堂所有已授權老師享有相同權限",async()=>{
    const sharedClass="class-shared-rights",sharedStudent="student-shared-rights",sharedBoard="23456789abcdefghjkmnpqrs",displayToken="23456789ABCDEFGHJKLMNPQR",inviteToken="ABCDEFGHJKLMNPQRSTUVWX29",now=Date.now(),peerUid="shared-monitor",peerDb=env.authenticatedContext(peerUid).database();
    const pages={main:{id:"main",order:0,createdAt:1,createdBy:"shared-teacher"}};
    await env.withSecurityRulesDisabled(async context=>update(ref(context.database()),{
      [`classes/${sharedClass}`]:{title:"同權限課堂",className:"",activityName:"",createdAt:now,expiresAt:now+10800000,updatedAt:now,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:1,displayToken,admins:{"shared-teacher":true,[peerUid]:true},studentOrder:{[sharedStudent]:0},boardPages:pages},
      [`students/${sharedStudent}`]:{classId:sharedClass,boardToken:sharedBoard,seatNumber:"01",displayName:"同學",enabled:true,locked:false,createdAt:1,updatedAt:1},
      [`boardLookup/${sharedBoard}`]:{classId:sharedClass,studentId:sharedStudent},
      [`boardPages/${sharedBoard}`]:pages,
      [`boards/${sharedBoard}/meta`]:{classId:sharedClass,studentId:sharedStudent,revision:0,updatedAt:1},
      [`userClasses/shared-teacher/${sharedClass}`]:true,
      [`userClasses/${peerUid}/${sharedClass}`]:true,
      [`displays/${displayToken}`]:{classId:sharedClass,active:false,updatedAt:1,updatedBy:"shared-teacher"}
    }));
    await assertSucceeds(get(ref(peerDb,`classes/${sharedClass}`)));
    await assertSucceeds(get(ref(peerDb,`userClasses/${peerUid}/${sharedClass}`)));
    await assertSucceeds(update(ref(peerDb,`classes/${sharedClass}`),{activityName:"由監看裝置更新",updatedAt:now}));
    await assertSucceeds(update(ref(peerDb,`students/${sharedStudent}`),{locked:true,updatedAt:now}));
    await assertSucceeds(set(ref(peerDb,`classes/${sharedClass}/pinnedStudents/${sharedStudent}`),true));
    await assertSucceeds(set(ref(peerDb,`boards/${sharedBoard}/teacherStrokes/shared_stroke`),{...stroke(peerUid),id:"shared_stroke"}));
    await assertSucceeds(set(ref(peerDb,`boards/${sharedBoard}/stickyNotes/shared_note`),{...stickyNote(peerUid),id:"shared_note"}));
    await assertSucceeds(set(ref(peerDb,`displays/${displayToken}`),{classId:sharedClass,active:true,studentId:sharedStudent,boardToken:sharedBoard,pageId:"main",label:"01 同學",followStudent:true,updatedAt:now,updatedBy:peerUid}));
    await assertSucceeds(set(ref(peerDb,`teacherInvites/${inviteToken}`),{classId:sharedClass,createdBy:peerUid,createdAt:now,expiresAt:now+600000}));
  });
  it("老師授權連結不能被第二個裝置重複使用",async()=>{const inviteToken="abcdefghjkmnpqrstuvwx234",now=Date.now(),teacherDb=env.authenticatedContext("teacher").database(),firstDb=env.authenticatedContext("first-monitor").database(),otherDb=env.authenticatedContext("other-monitor").database();await assertSucceeds(set(ref(teacherDb,`teacherInvites/${inviteToken}`),{classId,createdBy:"teacher",createdAt:now,expiresAt:now+600000}));await assertSucceeds(set(ref(firstDb,`teacherInvites/${inviteToken}/claimedBy`),"first-monitor"));await assertFails(set(ref(otherDb,`teacherInvites/${inviteToken}/claimedBy`),"other-monitor"));await assertFails(set(ref(otherDb,`teacherClaims/${classId}/other-monitor`),inviteToken));await assertFails(set(ref(otherDb,`classes/${classId}/admins/other-monitor`),true));});
  it("過期的老師授權連結不能被使用",async()=>{const inviteToken="23456789ABCDEFGHJKLMNPQR",otherDb=env.authenticatedContext("expired-monitor").database();await env.withSecurityRulesDisabled(async context=>set(ref(context.database(),`teacherInvites/${inviteToken}`),{classId,createdBy:"teacher",createdAt:1,expiresAt:2}));await assertFails(set(ref(otherDb,`teacherInvites/${inviteToken}/claimedBy`),"expired-monitor"));});
  it("六位數密鑰可授權不限數量的老師",async()=>{const unlimitedClass="class-unlimited",key="654321",now=Date.now();await env.withSecurityRulesDisabled(async context=>await update(ref(context.database()),{[`classes/${unlimitedClass}`]:{title:"不限老師",className:"",activityName:"",createdAt:now,expiresAt:now+10800000,updatedAt:now,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:0,admins:{"unlimited-teacher":true},studentOrder:{}},[`teacherKeys/${unlimitedClass}`]:key}));for(let i=1;i<=8;i++){const uid=`unlimited-teacher-${i}`,db=env.authenticatedContext(uid).database();await assertSucceeds(set(ref(db,`teacherKeyClaims/${unlimitedClass}/${uid}`),key));await assertSucceeds(set(ref(db,`classes/${unlimitedClass}/admins/${uid}`),true));await assertSucceeds(set(ref(db,`userClasses/${uid}/${unlimitedClass}`),true));await assertSucceeds(set(ref(db,`teacherKeyClaims/${unlimitedClass}/${uid}`),null));await assertSucceeds(get(ref(db,`classes/${unlimitedClass}`)));}});
  it("課程到期時間建立後不可延長",async()=>{const db=env.authenticatedContext("teacher").database(),current=(await get(ref(db,`classes/${classId}/expiresAt`))).val();await assertFails(set(ref(db,`classes/${classId}/expiresAt`),current+60000));});
  it("到期後禁止修改但允許老師完整刪除",async()=>{const expiredClass="expired-class",expiredStudent="expired-student",expiredBoard="ExpiredBoardToken23456789",now=Date.now(),pages={main:{id:"main",order:0,createdAt:now,createdBy:"expired-teacher"}};await env.withSecurityRulesDisabled(async context=>update(ref(context.database()),{[`classes/${expiredClass}`]:{title:"已到期",className:"",activityName:"",createdAt:now-10800001,expiresAt:now-1,updatedAt:now-1,status:"active",allowStudentWriting:true,allowStudentClear:false,showTeacherAnnotations:true,studentCount:1,admins:{"expired-teacher":true},studentOrder:{[expiredStudent]:0},boardPages:pages},[`students/${expiredStudent}`]:{classId:expiredClass,boardToken:expiredBoard,seatNumber:"01",displayName:"到期學生",studentUid:"expired-student-device",enabled:true,locked:false,createdAt:now-1,updatedAt:now-1},[`boardLookup/${expiredBoard}`]:{classId:expiredClass,studentId:expiredStudent},[`boardPages/${expiredBoard}`]:pages,[`boards/${expiredBoard}/meta`]:{classId:expiredClass,studentId:expiredStudent,revision:0,updatedAt:now-1},[`userClasses/expired-teacher/${expiredClass}`]:true}));const teacherDb=env.authenticatedContext("expired-teacher").database(),studentDb=env.authenticatedContext("expired-student-device").database();await assertSucceeds(get(ref(studentDb,`classes/${expiredClass}/expiresAt`)));await assertFails(update(ref(teacherDb,`classes/${expiredClass}`),{title:"不可修改"}));await assertFails(update(ref(studentDb,`students/${expiredStudent}`),{updatedAt:now}));await assertFails(set(ref(studentDb,`boards/${expiredBoard}/studentStrokes/stroke_1`),stroke("expired-student-device")));await assertFails(set(ref(teacherDb,`boards/${expiredBoard}/teacherStrokes/stroke_1`),stroke("expired-teacher")));await assertSucceeds(update(ref(teacherDb),{[`classes/${expiredClass}`]:null,[`students/${expiredStudent}`]:null,[`boardLookup/${expiredBoard}`]:null,[`boards/${expiredBoard}`]:null,[`boardPages/${expiredBoard}`]:null,[`userClasses/expired-teacher/${expiredClass}`]:null}));});
});
