import { ensureAnonymousUser } from "../firebase/auth.js";
import { cleanupExpiredClassroom, listAllClasses, listMyClasses, listPublicClassKeys, syncClassroomDirectories } from "../firebase/classroomRepository.js";
import { watchConnection } from "../firebase/connection.js";
import { createClassroomFlow } from "../home/createClassroomFlow.js";
import { getTeacherAccessKey } from "../firebase/teacherAccessRepository.js";
import { rememberTeacherSession } from "../teacher/localSession.js";
import { clearBrowserRecords, clearLegacyClassroomHistory } from "../utils/browserRecords.js";
import { formatClassroomRemaining } from "../utils/classroomExpiration.js";
import { countActiveClassrooms, isActiveClassroom } from "../utils/classroomStats.js";
import { bindDialogClose, confirmAction, explainError, toast } from "../utils/ui.js";

const list=document.querySelector("#classList"),allClassList=document.querySelector("#allClassList"),dialog=document.querySelector("#createDialog"),form=document.querySelector("#createClassForm"),activeCount=document.querySelector("#activeClassCount");let user,displayedClasses=[],remainingTimer;
bindDialogClose(dialog);
function renderAllClasses(classes){displayedClasses=classes;activeCount.textContent=countActiveClassrooms(classes);allClassList.innerHTML=classes.length?classes.map(c=>{const active=isActiveClassroom(c),keyLabel=c.teacherKey?`六位數密鑰：<strong>${escapeHtml(c.teacherKey)}</strong>`:'六位數密鑰：無權限查看';return `<article class="all-class-row"><div class="all-class-info"><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.className||'未設定班級')}・${c.studentCount||0} 位學生</p><div class="all-class-debug"><a class="button-link" href="./teacher.html?class=${encodeURIComponent(c.id)}">老師連結</a><span class="debug-key ${c.teacherKey?'':'muted'}">${keyLabel}</span><span class="debug-expiry">自動刪除剩餘：<strong>${escapeHtml(formatClassroomRemaining(c))}</strong></span></div></div><span class="badge ${active?'online':'disabled'}">${active?'進行中':'停用中'}</span></article>`;}).join(""):'<div class="empty">系統目前沒有課程。</div>';if(!remainingTimer)remainingTimer=setInterval(()=>renderAllClasses(displayedClasses),30000);}
async function load(){try{user ||= await ensureAnonymousUser();}catch(e){const message=`<div class="notice">${escapeHtml(explainError(e))}</div>`;list.innerHTML=message;allClassList.innerHTML=message;activeCount.textContent="—";return;}let active=[];try{const classes=await listMyClasses(user.uid);for(const classroom of classes){try{if(await cleanupExpiredClassroom(classroom.id,user.uid,classroom))continue;}catch(error){console.error(error);}active.push(classroom);}list.innerHTML=active.length?active.map(c=>`<article class="class-card"><span class="badge ${c.status==='active'?'online':''}">${c.status==='active'?'進行中':'已結束'}</span><h3>${escapeHtml(c.title)}</h3><p>${escapeHtml(c.className||'未設定班級')}・${c.studentCount||0} 位學生</p><div class="card-actions"><a class="button-link" href="./teacher.html?class=${c.id}">課堂設定</a><a class="button-link" href="./monitor.html?class=${c.id}">多格監看</a></div></article>`).join(""):'<div class="empty">這個瀏覽器尚未建立課堂。</div>';}catch(e){list.innerHTML=`<div class="notice">${escapeHtml(explainError(e))}</div>`;}try{await syncClassroomDirectories(active);}catch(e){console.error("系統課程清單補登失敗：",e);}try{const managedIds=new Set(active.map(c=>c.id)),classes=await listAllClasses();await Promise.all(classes.map(async c=>{if(!managedIds.has(c.id))return;try{c.teacherKey=await getTeacherAccessKey(c.id);}catch(error){console.error("老師密鑰讀取失敗：",error);}}));renderAllClasses(classes);}catch(e){allClassList.innerHTML=`<div class="notice">${escapeHtml(explainError(e))}</div>`;activeCount.textContent="—";}}
function escapeHtml(v){const d=document.createElement("div");d.textContent=String(v);return d.innerHTML;}
document.querySelector("#createClassBtn").onclick=()=>dialog.showModal();document.querySelector("#refreshBtn").onclick=load;
document.querySelector("#debugKeyBtn").onclick=async(e)=>{const button=e.currentTarget,panel=document.querySelector("#debugKeyPanel"),keyList=document.querySelector("#debugFirebaseKeyList");if(!panel.hidden){panel.hidden=true;button.setAttribute("aria-expanded","false");return;}button.disabled=true;try{user ||= await ensureAnonymousUser();const keys=await listPublicClassKeys();keyList.innerHTML=keys.length?`<ol>${keys.map(key=>`<li><code>${escapeHtml(key)}</code></li>`).join("")}</ol>`:'<p class="muted">publicClasses 目前沒有第一層 Key。</p>';panel.hidden=false;button.setAttribute("aria-expanded","true");}catch(error){toast(explainError(error),"error");}finally{button.disabled=false;}};
document.querySelector("#clearBrowserRecordsBtn").onclick=()=>{if(!confirmAction("這會清除本網站儲存在此瀏覽器的老師登入暫存與介面偏好，但不會刪除資料庫中的課堂與作品。若未保存老師網址與六位數密鑰，可能無法再次進入課程。確定清除？"))return;if(!clearBrowserRecords())return toast("無法清除瀏覽記錄，請檢查瀏覽器儲存空間設定。","error");toast("已清除本網站的瀏覽記錄。")};
form.addEventListener("submit",async(e)=>{e.preventDefault();const button=form.querySelector("button.primary"),values=Object.fromEntries(new FormData(form));button.disabled=true;try{const result=await createClassroomFlow(values);user=result.user;rememberTeacherSession(result.id,user.uid);location.replace(`./teacher.html?class=${result.id}`);}catch(error){toast(explainError(error),"error");button.disabled=false;}});
clearLegacyClassroomHistory();watchConnection(document.querySelector("#connectionBadge"));load();
addEventListener("pagehide",()=>{clearInterval(remainingTimer);remainingTimer=null;});
addEventListener("pageshow",()=>{if(displayedClasses.length&&!remainingTimer)renderAllClasses(displayedClasses);});
