import { ensureAnonymousUser } from "../firebase/auth.js";
import { setStudentPinned, watchClassroom } from "../firebase/classroomRepository.js";
import { getStudents, updateStudent } from "../firebase/studentRepository.js";
import { clearLayer, hasAnswers, removeStroke, saveStroke, subscribeLayer } from "../firebase/boardRepository.js";
import { watchPresence } from "../firebase/presenceRepository.js";
import { watchConnection } from "../firebase/connection.js";
import { claimTeacherInvite } from "../firebase/teacherAccessRepository.js";
import { BoardEngine } from "../canvas/BoardEngine.js";
import { normalizeGridSize, paginateStudents, prioritizePinned } from "../monitor/studentView.js";
import { param } from "../utils/url.js";
import { confirmAction, explainError, toast } from "../utils/ui.js";

const classId=param("class"),inviteToken=param("invite"),grid=document.querySelector("#monitorGrid"),state=document.querySelector("#monitorState"),dialog=document.querySelector("#reviewDialog"),monitorToolbar=document.querySelector("#monitorToolbar"),showMonitorToolbar=document.querySelector("#showMonitorToolbar");let user,classroom,students=[],presence={},page=0,gridSize=loadGridSize(),previewOffs=[],previewObservers=[],reviewOffs=[],reviewEngine,currentStudent,rotateTimer,presenceOff;
watchConnection(document.querySelector("#connectionBadge"));document.querySelector("#teacherLink").href=`./teacher.html?class=${encodeURIComponent(classId||"")}`;
function loadGridSize(){try{return normalizeGridSize(localStorage.getItem(`classpad-grid-size:${classId}`));}catch{return 4;}}
function setToolbarHidden(hidden){monitorToolbar.hidden=hidden;showMonitorToolbar.hidden=!hidden;document.body.classList.toggle("toolbar-hidden",hidden);try{localStorage.setItem("classpad-monitor-toolbar-hidden",String(hidden));}catch{}}
document.querySelector("#hideMonitorToolbar").onclick=()=>setToolbarHidden(true);showMonitorToolbar.onclick=()=>setToolbarHidden(false);try{setToolbarHidden(localStorage.getItem("classpad-monitor-toolbar-hidden")==="true");}catch{setToolbarHidden(false);}
function filtered(){const q=document.querySelector("#searchInput").value.trim().toLowerCase(),matches=students.filter(s=>(!q||`${s.seatNumber} ${s.displayName}`.toLowerCase().includes(q))&&(!document.querySelector("#onlineOnly").checked||presence[s.id]?.online)&&(!document.querySelector("#answeredOnly").checked||s.hasAnswer));return prioritizePinned(matches,classroom?.pinnedStudents);}
function drawPreview(canvas,maps){const rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;if(canvas.width!==Math.round(rect.width*dpr)||canvas.height!==Math.round(rect.height*dpr)){canvas.width=Math.round(rect.width*dpr);canvas.height=Math.round(rect.height*dpr);}const ctx=canvas.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,rect.width,rect.height);ctx.fillStyle="#fff";ctx.fillRect(0,0,rect.width,rect.height);for(const map of maps)for(const stroke of map.values()){const pts=stroke.points||[];ctx.strokeStyle=stroke.color;ctx.globalAlpha=stroke.opacity??1;ctx.lineWidth=Math.max(1,stroke.width*.35);ctx.lineCap="round";ctx.lineJoin="round";ctx.beginPath();pts.forEach((p,i)=>i?ctx.lineTo(p[0]*rect.width,p[1]*rect.height):ctx.moveTo(p[0]*rect.width,p[1]*rect.height));ctx.stroke();}ctx.globalAlpha=1;}
function clearPreviews(){previewOffs.forEach(x=>x());previewOffs=[];previewObservers.forEach(x=>x.disconnect());previewObservers=[];}
function render(){clearPreviews();const list=filtered(),view=paginateStudents(list,page,gridSize),visible=view.students,pinned=classroom?.pinnedStudents||{};page=view.page;grid.dataset.size=String(gridSize);document.querySelectorAll("[data-grid-size]").forEach(button=>button.setAttribute("aria-pressed",String(Number(button.dataset.gridSize)===gridSize)));document.querySelector("#pageLabel").textContent=`第 ${page+1} / ${view.pages} 頁`;document.querySelector("#prevPage").disabled=page===0;document.querySelector("#nextPage").disabled=page>=view.pages-1;state.hidden=visible.length>0;state.textContent=list.length?"這一頁沒有學生。":"沒有符合條件的學生。";grid.hidden=!visible.length;grid.innerHTML=visible.map(s=>`<article class="preview-card" data-id="${s.id}"><div class="preview-head"><strong>${escapeHtml(s.seatNumber)} ${escapeHtml(s.displayName)}</strong><span class="preview-actions"><button class="pin-button" aria-label="${pinned[s.id]?'取消釘選':'釘選'} ${escapeHtml(s.displayName)}" aria-pressed="${Boolean(pinned[s.id])}">${pinned[s.id]?'📌 已釘選':'📌 釘選'}</button><span class="badge ${presence[s.id]?.online?'online':'offline'}">${presence[s.id]?.online?(presence[s.id]?.drawing?'書寫中':'在線'):'離線'}</span>${s.locked?' <span class="badge error">鎖定</span>':''}</span></div><canvas class="preview-canvas"></canvas><button class="enlarge primary">放大批注</button></article>`).join("");
  visible.forEach(s=>{const card=grid.querySelector(`[data-id="${s.id}"]`),canvas=card.querySelector("canvas"),maps=[new Map(),new Map()];const redraw=()=>requestAnimationFrame(()=>drawPreview(canvas,maps));previewOffs.push(subscribeLayer(s.boardToken,"studentStrokes",{add:(id,v)=>{maps[0].set(id,v);s.hasAnswer=true;redraw();},remove:id=>{maps[0].delete(id);s.hasAnswer=maps[0].size>0;redraw();}}),subscribeLayer(s.boardToken,"teacherStrokes",{add:(id,v)=>{maps[1].set(id,v);redraw();},remove:id=>{maps[1].delete(id);redraw();}}));card.querySelector(".enlarge").onclick=()=>openReview(s);card.querySelector(".pin-button").onclick=async()=>{const next=!Boolean(classroom.pinnedStudents?.[s.id]);try{await setStudentPinned(classId,s.id,next);classroom.pinnedStudents={...(classroom.pinnedStudents||{})};if(next)classroom.pinnedStudents[s.id]=true;else delete classroom.pinnedStudents[s.id];page=0;render();}catch(e){toast(explainError(e),"error");}};const observer=new ResizeObserver(redraw);observer.observe(canvas);previewObservers.push(observer);});}
function escapeHtml(v){const d=document.createElement("div");d.textContent=v;return d.innerHTML;}
async function loadStudents(){try{students=await getStudents(classroom);await Promise.all(students.map(async s=>{s.hasAnswer=await hasAnswers(s.boardToken);}));render();}catch(e){state.textContent=explainError(e);}}
async function init(){if(!classId){state.textContent="網址缺少課堂編號。";return;}try{user=await ensureAnonymousUser();if(inviteToken){state.textContent="正在授權這台裝置…";await claimTeacherInvite(classId,inviteToken,user.uid);const cleanUrl=new URL(location.href);cleanUrl.searchParams.delete("invite");history.replaceState(null,"",cleanUrl);toast("這台裝置已取得老師權限。");}watchClassroom(classId,(value)=>{if(!value){state.textContent="課堂不存在或權限不足。";return;}const previousOrder=JSON.stringify(classroom?.studentOrder||{});classroom=value;document.querySelector("#classTitle").textContent=value.title;if(!students.length||previousOrder!==JSON.stringify(value.studentOrder||{}))loadStudents();else render();});presenceOff=watchPresence(classId,(value)=>{presence=value;render();});}catch(e){state.textContent=explainError(e);}}
async function openReview(student){currentStudent=student;clearPreviews();document.querySelector("#reviewName").textContent=`${student.seatNumber} ${student.displayName}`;document.querySelector("#reviewPresence").textContent=presence[student.id]?.online?"在線":"離線";document.querySelector("#toggleLock").textContent=student.locked?"解鎖白板":"鎖定白板";dialog.showModal();reviewEngine=new BoardEngine({stage:document.querySelector("#reviewStage"),backgroundCanvas:document.querySelector("#reviewBackground"),studentCanvas:document.querySelector("#reviewStudent"),teacherCanvas:document.querySelector("#reviewTeacher"),editableLayer:"teacherStrokes",uid:user.uid,onComplete:stroke=>saveStroke(student.boardToken,"teacherStrokes",stroke).catch(e=>toast(explainError(e),"error")),onRemove:id=>removeStroke(student.boardToken,"teacherStrokes",id).catch(e=>toast(explainError(e),"error"))});reviewOffs=[subscribeLayer(student.boardToken,"studentStrokes",{add:(id,s)=>reviewEngine.addStroke("studentStrokes",id,s),remove:id=>reviewEngine.removeStroke("studentStrokes",id)}),subscribeLayer(student.boardToken,"teacherStrokes",{add:(id,s)=>reviewEngine.addStroke("teacherStrokes",id,s),remove:id=>reviewEngine.removeStroke("teacherStrokes",id)})];}
function closeReview(){reviewOffs.forEach(x=>x());reviewOffs=[];reviewEngine?.destroy();reviewEngine=null;dialog.close();render();}
document.querySelector("#closeReview").onclick=closeReview;dialog.addEventListener("cancel",e=>{e.preventDefault();closeReview();});dialog.querySelectorAll("button[data-tool]").forEach(b=>b.onclick=()=>{dialog.querySelectorAll("button[data-tool]").forEach(x=>x.classList.remove("active"));b.classList.add("active");reviewEngine.setTool(b.dataset.tool);});document.querySelector("#reviewColor").oninput=e=>reviewEngine.setColor(e.target.value);document.querySelector("#reviewWidth").oninput=e=>reviewEngine.setWidth(e.target.value);document.querySelector("#reviewUndo").onclick=()=>reviewEngine.undo();document.querySelector("#reviewRedo").onclick=()=>reviewEngine.redo();document.querySelector("#reviewResetZoom").onclick=()=>reviewEngine.resetZoom();
document.querySelector("#toggleLock").onclick=async()=>{try{await updateStudent(currentStudent.id,{locked:!currentStudent.locked});currentStudent.locked=!currentStudent.locked;document.querySelector("#toggleLock").textContent=currentStudent.locked?"解鎖白板":"鎖定白板";}catch(e){toast(explainError(e),"error");}};document.querySelector("#clearTeacher").onclick=async()=>{if(confirmAction("確定清除全部老師批注？")){await clearLayer(currentStudent.boardToken,"teacherStrokes");reviewEngine.clearLayerLocal("teacherStrokes");}};
document.querySelector("#exportPng").onclick=()=>{const source=reviewEngine.exportCanvas(),out=document.createElement("canvas");out.width=1600;out.height=1280;const ctx=out.getContext("2d");ctx.fillStyle="#fff";ctx.fillRect(0,0,out.width,out.height);ctx.fillStyle="#173f5f";ctx.font="bold 30px sans-serif";ctx.fillText(`${currentStudent.seatNumber} ${currentStudent.displayName}　${new Date().toLocaleString('zh-TW')}`,30,48);ctx.drawImage(source,0,80,1600,1200);out.toBlob(blob=>{const a=document.createElement("a"),d=new Date(),stamp=d.toISOString().slice(0,16).replaceAll(/[-:T]/g,"");a.href=URL.createObjectURL(blob);a.download=`${currentStudent.seatNumber}-${currentStudent.displayName}-${stamp}.png`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);});};
for(const id of ["searchInput","onlineOnly","answeredOnly"])document.querySelector(`#${id}`).addEventListener(id==="searchInput"?"input":"change",()=>{page=0;render();});document.querySelectorAll("[data-grid-size]").forEach(button=>button.onclick=()=>{gridSize=normalizeGridSize(button.dataset.gridSize);page=0;try{localStorage.setItem(`classpad-grid-size:${classId}`,String(gridSize));}catch{}render();});document.querySelector("#prevPage").onclick=()=>{page--;render();};document.querySelector("#nextPage").onclick=()=>{page++;render();};document.querySelector("#autoRotate").onchange=e=>{clearInterval(rotateTimer);if(e.target.checked)rotateTimer=setInterval(()=>{const pages=Math.max(1,Math.ceil(filtered().length/gridSize));page=(page+1)%pages;render();},10000);};addEventListener("pagehide",()=>{clearPreviews();presenceOff?.();reviewOffs.forEach(x=>x());clearInterval(rotateTimer);});init();
