import { ensureAnonymousUser } from "../firebase/auth.js";
import { bindStudent, resolveBoard, watchStudent } from "../firebase/studentRepository.js";
import { clearActive, publishActive, removeStroke, saveStroke, subscribeLayer, subscribeStickyNotes, watchActive } from "../firebase/boardRepository.js";
import { setDrawing, startPresence } from "../firebase/presenceRepository.js";
import { watchConnection } from "../firebase/connection.js";
import { BoardEngine } from "../canvas/BoardEngine.js";
import { StickyNotesLayer } from "../notes/StickyNotesLayer.js";
import { param } from "../utils/url.js";
import { explainError, toast } from "../utils/ui.js";

const token=param("board"),message=document.querySelector("#boardMessage"),stage=document.querySelector("#boardStage"),toolbar=document.querySelector("#studentToolbar"),sync=document.querySelector("#syncBadge");let user,student,engine,stickyNotes,cleanup=[];let activeTimer;
watchConnection(document.querySelector("#connectionBadge"));
function setMessage(text){message.textContent=text;message.hidden=false;stage.hidden=true;toolbar.hidden=true;}
function setSync(text,type=""){sync.textContent=text;sync.className=`badge ${type}`;}
async function init(){if(!token)return setMessage("無效連結：缺少白板識別碼。");try{user=await ensureAnonymousUser();student=await resolveBoard(token);if(!student)return setMessage("白板不存在，請向老師索取新的連結。");if(!student.enabled)return setMessage("此白板已停用，請聯絡老師。");if(student.studentUid&&student.studentUid!==user.uid)return setMessage("此白板已綁定其他裝置，請聯絡老師解除裝置綁定。");if(!student.studentUid){const bound=await bindStudent(student.id,user.uid);if(!bound)return setMessage("白板剛被其他裝置綁定，請聯絡老師。");student.studentUid=user.uid;}
  document.querySelector("#studentName").textContent=student.displayName;document.querySelector("#seatNumber").textContent=` ${student.seatNumber}`;message.hidden=true;stage.hidden=false;toolbar.hidden=false;
  stickyNotes=new StickyNotesLayer({container:document.querySelector("#studentStickyLayer")});engine=new BoardEngine({stage,backgroundCanvas:document.querySelector("#backgroundCanvas"),studentCanvas:document.querySelector("#studentCanvas"),teacherCanvas:document.querySelector("#teacherCanvas"),editableLayer:"studentStrokes",uid:user.uid,onComplete:async stroke=>{setSync("同步中");try{await saveStroke(token,"studentStrokes",stroke);setSync("已同步","synced");}catch(e){setSync("同步失敗","error");toast(explainError(e),"error");}},onRemove:async id=>{setSync("同步中");try{await removeStroke(token,"studentStrokes",id);setSync("已同步","synced");}catch(e){setSync("同步失敗","error");}},onActive:stroke=>{setDrawing(student.classId,student.id,Boolean(stroke));clearTimeout(activeTimer);activeTimer=setTimeout(()=>stroke?publishActive(token,"student",user.uid,{...stroke,points:stroke.points.slice(-80),updatedAt:Date.now()}):clearActive(token,"student",user.uid),100);},onViewChange:view=>stickyNotes.setViewport(view)});
  cleanup.push(subscribeLayer(token,"studentStrokes",{add:(id,s)=>engine.addStroke("studentStrokes",id,s),remove:id=>engine.removeStroke("studentStrokes",id)}));cleanup.push(subscribeLayer(token,"teacherStrokes",{add:(id,s)=>engine.addStroke("teacherStrokes",id,s),remove:id=>engine.removeStroke("teacherStrokes",id)}));cleanup.push(subscribeStickyNotes(token,{add:(id,note)=>stickyNotes.upsert(id,note),change:(id,note)=>stickyNotes.upsert(id,note),remove:id=>stickyNotes.remove(id)}));cleanup.push(watchStudent(student.id,(value)=>{if(!value)return setMessage("白板已被老師刪除。");student=value;const locked=value.locked||!value.enabled;engine.setEnabled(!locked);document.querySelector("#lockBadge").hidden=!locked;if(value.studentUid!==user.uid)setMessage("此白板的裝置綁定已變更，請聯絡老師。");}));cleanup.push(await startPresence(student.classId,student.id,user.uid));setSync("已同步","synced");bindToolbar();
}catch(e){setMessage(explainError(e));setSync("開啟失敗","error");}}
function bindToolbar(){toolbar.querySelectorAll("button[data-tool]").forEach(b=>b.onclick=()=>{toolbar.querySelectorAll("button[data-tool]").forEach(x=>x.classList.remove("active"));b.classList.add("active");engine.setTool(b.dataset.tool);});document.querySelector("#colorInput").oninput=e=>engine.setColor(e.target.value);document.querySelector("#widthInput").oninput=e=>engine.setWidth(e.target.value);document.querySelector("#undoBtn").onclick=()=>engine.undo();document.querySelector("#redoBtn").onclick=()=>engine.redo();document.querySelector("#resetZoomBtn").onclick=()=>engine.resetZoom();}
addEventListener("pagehide",()=>{cleanup.forEach(fn=>fn?.());if(user&&student)clearActive(token,"student",user.uid);stickyNotes?.destroy();engine?.destroy();});init();
