import QRCode from "qrcode";
import { ensureAnonymousUser } from "../firebase/auth.js";
import { closeClassroom, deleteClassroom, saveClassroom, watchClassroom } from "../firebase/classroomRepository.js";
import { addStudents, deleteStudent, getStudents, MAX_STUDENTS, regenerateBoard, resetBinding, updateStudent } from "../firebase/studentRepository.js";
import { clearLayer } from "../firebase/boardRepository.js";
import { claimTeacherKey, ensureTeacherAccessKey, MAX_TEACHER_DEVICES, resetOtherTeacherDevices } from "../firebase/teacherAccessRepository.js";
import { ensureClassDisplay } from "../firebase/displayRepository.js";
import { watchConnection } from "../firebase/connection.js";
import { parseStudentList } from "../teacher/studentImporter.js";
import { forgetTeacherSession, readTeacherSession, rememberTeacherSession } from "../teacher/localSession.js";
import { downloadCsv } from "../utils/csv.js";
import { pageUrl, param } from "../utils/url.js";
import { bindDialogClose, confirmAction, explainError, toast } from "../utils/ui.js";

const classId=param("class"),state=document.querySelector("#pageState"),content=document.querySelector("#teacherContent"),login=document.querySelector("#teacherLogin"),table=document.querySelector("#studentTable"),qrDialog=document.querySelector("#qrDialog");let user,classroom,teacherKey,classOff,retryTimer,accessRetries=0,students=[];let loading=false;
const teacherUrl=pageUrl("./teacher.html",{class:classId||""});
bindDialogClose(qrDialog);document.querySelector("#monitorLink").href=`./monitor.html?class=${encodeURIComponent(classId||"")}`;document.querySelector("#teacherAccessUrl").value=teacherUrl;watchConnection(document.querySelector("#connectionBadge"));
const studentUrl=(s)=>pageUrl("./student.html",{board:s.boardToken});
function safe(v){const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML;}
async function refreshStudents(){if(loading||!classroom)return;loading=true;try{students=await getStudents(classroom);renderStudents();}catch(e){toast(explainError(e),"error");}finally{loading=false;}}
function renderStudents(){document.querySelector("#studentCount").textContent=`(${students.length}/${MAX_STUDENTS})`;document.querySelector("#emptyStudents").hidden=students.length>0;table.innerHTML=students.map(s=>`<tr data-id="${s.id}"><td>${safe(s.seatNumber)}</td><td>${safe(s.displayName)}</td><td><span class="badge ${s.locked?'error':'online'}">${s.locked?'已鎖定':s.enabled?'可使用':'已停用'}</span></td><td>${s.studentUid?'<span class="badge">已綁定</span>':'<span class="muted">未綁定</span>'}</td><td><div class="row-actions"><button data-action="copy">複製網址</button><button data-action="qr">QR Code</button><button data-action="lock">${s.locked?'解鎖':'鎖定'}</button><button data-action="unbind">解除綁定</button><button data-action="regenerate">重建網址</button><button data-action="clear">清除白板</button><button class="danger-outline" data-action="delete">刪除</button></div></td></tr>`).join("");}
async function loadTeacherKey(){if(teacherKey)return teacherKey;teacherKey=await ensureTeacherAccessKey(classId);document.querySelector("#teacherAccessKey").textContent=teacherKey;return teacherKey;}
function showLogin(){const saved=readTeacherSession(classId);if(saved?.uid===user?.uid&&accessRetries<3){const delay=250*(2**accessRetries++);state.hidden=false;state.textContent="正在恢復這個瀏覽器的老師權限…";clearTimeout(retryTimer);retryTimer=setTimeout(startClassWatch,delay);return;}state.hidden=true;content.hidden=true;login.hidden=false;document.querySelector("#teacherKeyInput").focus();}
function startClassWatch(){classOff?.();state.hidden=false;state.textContent="正在載入課堂…";classOff=watchClassroom(classId,showClass,showLogin);}
function showClass(value){classroom=value;if(!value){state.hidden=false;state.textContent="課堂不存在，或已被刪除。";content.hidden=true;login.hidden=true;return;}accessRetries=0;rememberTeacherSession(classId,user.uid);state.hidden=true;login.hidden=true;content.hidden=false;document.querySelector("#classTitle").textContent=value.title;document.querySelector("#classMeta").textContent=`${value.className||'未設定班級'}・${value.activityName||'未設定活動'}・${value.status==='active'?'進行中':'已結束'}`;const deviceCount=Object.keys(value.admins||{}).length,shareButton=document.querySelector("#shareMonitorBtn"),resetButton=document.querySelector("#resetMonitorDevicesBtn");shareButton.textContent=`老師連結 QR (${deviceCount}/${MAX_TEACHER_DEVICES})`;resetButton.textContent=`解除其他老師裝置 (${Math.max(0,deviceCount-1)})`;resetButton.disabled=deviceCount<=1;const f=document.querySelector("#settingsForm");for(const name of ["title","className","activityName"])f.elements[name].value=value[name]||"";for(const name of ["allowStudentWriting","allowStudentClear","showTeacherAnnotations"])f.elements[name].checked=value[name]!==false;document.querySelector("#closeClassBtn").textContent=value.status==='active'?"結束課堂":"重新開啟";loadTeacherKey().catch(x=>toast(explainError(x),"error"));refreshStudents();}
async function init(){if(!classId){state.textContent="網址缺少課堂編號。";return;}try{user=await ensureAnonymousUser();startClassWatch();}catch(e){state.textContent=explainError(e);}}
document.querySelector("#settingsForm").addEventListener("submit",async(e)=>{e.preventDefault();const f=e.currentTarget;try{await saveClassroom(classId,{title:f.title.value.trim(),className:f.className.value.trim(),activityName:f.activityName.value.trim(),allowStudentWriting:f.allowStudentWriting.checked,allowStudentClear:f.allowStudentClear.checked,showTeacherAnnotations:f.showTeacherAnnotations.checked});toast("課堂設定已儲存。");}catch(x){toast(explainError(x),"error");}});
document.querySelector("#importForm").addEventListener("submit",async(e)=>{e.preventDefault();try{const rows=parseStudentList(e.currentTarget.students.value,(classroom.studentCount||0)+1);if(!rows.length)throw new Error("請至少輸入一位學生。");await addStudents(classId,classroom,rows);e.currentTarget.reset();toast(`已加入 ${rows.length} 位學生。`);}catch(x){toast(explainError(x),"error");}});
table.addEventListener("click",async(e)=>{const button=e.target.closest("button");if(!button)return;const s=students.find(x=>x.id===button.closest("tr").dataset.id);try{switch(button.dataset.action){case"copy":await navigator.clipboard.writeText(studentUrl(s));toast("網址已複製。");break;case"qr":document.querySelector("#qrTitle").textContent=`${s.seatNumber} ${s.displayName}`;document.querySelector("#qrHint").hidden=true;document.querySelector("#qrUrl").textContent=studentUrl(s);await QRCode.toCanvas(document.querySelector("#qrCanvas"),studentUrl(s),{width:280,margin:1});qrDialog.showModal();break;case"lock":await updateStudent(s.id,{locked:!s.locked});break;case"unbind":if(confirmAction("解除後，下一個開啟連結的裝置會取得編輯權限。確定解除？"))await resetBinding(s.id);break;case"regenerate":if(confirmAction("舊網址與舊白板會永久刪除，確定重建？")){await regenerateBoard(classId,s);toast("已產生新網址。");}break;case"clear":if(confirmAction("確定清除這位學生的全部筆跡？")){await clearLayer(s.boardToken,"studentStrokes");toast("學生白板已清除。");}break;case"delete":if(confirmAction("確定刪除學生與全部白板資料？"))await deleteStudent(classId,classroom,s);break;}if(!["copy","qr"].includes(button.dataset.action))await refreshStudents();}catch(x){toast(explainError(x),"error");}});
document.querySelector("#copyQrUrlBtn").onclick=async()=>{await navigator.clipboard.writeText(document.querySelector("#qrUrl").textContent);toast("網址已複製。");};
document.querySelector("#downloadCsvBtn").onclick=()=>downloadCsv([["座號","姓名","白板網址"],...students.map(s=>[s.seatNumber,s.displayName,studentUrl(s)])],`${classroom.title}-學生連結.csv`);
document.querySelector("#teacherLoginForm").addEventListener("submit",async(e)=>{e.preventDefault();const button=e.currentTarget.querySelector("button"),input=document.querySelector("#teacherKeyInput");button.disabled=true;try{await claimTeacherKey(classId,input.value,user.uid);rememberTeacherSession(classId,user.uid);input.value="";toast("密鑰正確，這台裝置已取得完整老師權限。");startClassWatch();}catch(x){toast(explainError(x),"error");input.select();}finally{button.disabled=false;}});
document.querySelector("#teacherKeyInput").addEventListener("input",e=>{e.target.value=e.target.value.replace(/\D/g,"").slice(0,6);});
document.querySelector("#copyTeacherLinkBtn").onclick=async()=>{try{await navigator.clipboard.writeText(teacherUrl);toast("老師連結已複製。");}catch(x){toast(explainError(x),"error");}};
document.querySelector("#copyTeacherAccessBtn").onclick=async()=>{try{const key=await loadTeacherKey();await navigator.clipboard.writeText(`老師連結：${teacherUrl}\n六位數密鑰：${key}`);toast("老師連結與密鑰已複製。");}catch(x){toast(explainError(x),"error");}};
document.querySelector("#shareMonitorBtn").onclick=async()=>{try{const key=await loadTeacherKey(),hint=document.querySelector("#qrHint");document.querySelector("#qrTitle").textContent="老師管理連結";hint.textContent=`六位數老師密鑰：${key}（不遮蔽）。開啟連結並輸入密鑰後，即取得相同完整管理權限；每個課堂最多 ${MAX_TEACHER_DEVICES} 台老師裝置。`;hint.hidden=false;document.querySelector("#qrUrl").textContent=teacherUrl;await QRCode.toCanvas(document.querySelector("#qrCanvas"),teacherUrl,{width:280,margin:1});qrDialog.showModal();}catch(x){toast(explainError(x),"error");}};
document.querySelector("#shareDisplayBtn").onclick=async()=>{try{const token=await ensureClassDisplay(classId,user.uid),url=pageUrl("./display.html",{display:token}),hint=document.querySelector("#qrHint");classroom.displayToken=token;document.querySelector("#qrTitle").textContent="被動展示畫面";hint.textContent="同一網址可同時開啟在不限數量的電腦、電視或平板。展示畫面不需操作，老師投影學生後會全部同步顯示；解除投影時會恢復黑畫面。";hint.hidden=false;document.querySelector("#qrUrl").textContent=url;await QRCode.toCanvas(document.querySelector("#qrCanvas"),url,{width:280,margin:1});qrDialog.showModal();}catch(x){toast(explainError(x),"error");}};
document.querySelector("#resetMonitorDevicesBtn").onclick=async(e)=>{if(!confirmAction("確定解除其他所有老師裝置？目前這台裝置會保留，其他裝置將立即失去權限；之後仍可用老師連結與密鑰重新登入。"))return;const button=e.currentTarget;button.disabled=true;try{const removed=await resetOtherTeacherDevices(classId,user.uid);classroom.admins={[user.uid]:true};button.textContent="解除其他老師裝置 (0)";toast(removed?`已解除 ${removed} 台其他老師裝置，可用老師連結與密鑰重新登入。`:"目前沒有其他老師裝置。");}catch(x){button.disabled=Object.keys(classroom?.admins||{}).length<=1;toast(explainError(x),"error");}};
document.querySelector("#printQrBtn").onclick=async()=>{if(!students.length)return toast("尚未加入學生。");const win=open("","_blank");const cards=[];for(const s of students){const data=await QRCode.toDataURL(studentUrl(s),{width:320,margin:1});cards.push(`<article><img src="${data}"><h2>${safe(s.seatNumber)} ${safe(s.displayName)}</h2></article>`);}win.document.write(`<title>${safe(classroom.title)} QR Code</title><style>body{font-family:sans-serif;display:grid;grid-template-columns:1fr 1fr;gap:30px}article{text-align:center;break-inside:avoid}img{width:240px}</style>${cards.join("")}<script>onload=()=>print()<\/script>`);win.document.close();};
document.querySelector("#closeClassBtn").onclick=async()=>{try{await closeClassroom(classId,classroom.status==='active');}catch(x){toast(explainError(x),"error");}};
document.querySelector("#deleteClassBtn").onclick=async()=>{if(!confirmAction("這會永久刪除課堂、名單與全部白板，無法復原。確定刪除？"))return;try{await deleteClassroom(classId,user.uid,classroom,students);forgetTeacherSession(classId);location.href="./";}catch(x){toast(explainError(x),"error");}};
addEventListener("pagehide",()=>{clearTimeout(retryTimer);classOff?.();});
init();
